import { DEFAULT_NOTIFICATION_HTML } from './email'
import {
  type Control,
  wysiwyg,
  templatePicker,
  border,
  borderRadius,
  boxShadow,
  choose,
  code,
  color,
  heading,
  json,
  number,
  opts,
  padding,
  repeater,
  section,
  select,
  slider,
  switcher,
  text,
  textarea,
  typography,
  url,
  dimensions,
} from '@blockwright/core'

const W = '{{WRAPPER}}'
const F = `${W} .bw-field`
const L = `${W} .bw-field-label`
const BTN = `${W} .bw-form-submit, ${W} .bw-step-next`
const BTN_H = `${W} .bw-form-submit:hover, ${W} .bw-step-next:hover, ${W} .bw-form-submit:focus-visible, ${W} .bw-step-next:focus-visible`
const PREV = `${W} .bw-step-prev`

export const FIELD_TYPES = opts({
  text: 'Text',
  email: 'Email',
  textarea: 'Textarea',
  tel: 'Phone',
  number: 'Number',
  url: 'URL',
  date: 'Date',
  time: 'Time',
  select: 'Select',
  radio: 'Radio',
  checkbox: 'Checkbox',
  acceptance: 'Acceptance',
  rating: 'Rating',
  range: 'Range slider',
  password: 'Password',
  hidden: 'Hidden',
  html: 'HTML',
  step: 'Step',
  honeypot: 'Honeypot (spam trap)',
})

const WIDTH_OPTIONS = opts({ '': 'Default', '100': '100%', '80': '80%', '75': '75%', '66': '66%', '60': '60%', '50': '50%', '40': '40%', '33': '33%', '25': '25%', '20': '20%' })

const noOptions = { 'field_type!': ['checkbox', 'radio', 'select', 'acceptance', 'html', 'step', 'hidden', 'honeypot', 'rating'] }

export const fieldControls: Control[] = [
  select('field_type', { label: 'Type', options: FIELD_TYPES, default: 'text' }),
  text('field_label', { label: 'Label', default: '', condition: { 'field_type!': ['hidden', 'honeypot'] } }),
  text('placeholder', { label: 'Placeholder', condition: { field_type: ['text', 'email', 'textarea', 'url', 'tel', 'number', 'password', 'select'] } }),
  switcher('required', { returnValue: 'true',  label: 'Required', condition: { 'field_type!': ['html', 'step', 'hidden', 'honeypot'] } }),
  textarea('field_options', {
    label: 'Options',
    description: 'One option per line. Use "Label|value" to set a different value.',
    condition: { field_type: ['select', 'radio', 'checkbox'] },
  }),
  switcher('allow_multiple', { returnValue: 'true',  label: 'Multiple selection', condition: { field_type: 'select' } }),
  number('select_size', { label: 'Rows', condition: { field_type: 'select', allow_multiple: 'true' } }),
  switcher('inline_list', { returnValue: 'true',  label: 'Inline list', condition: { field_type: ['radio', 'checkbox'] } }),
  text('acceptance_text', { label: 'Acceptance text', condition: { field_type: 'acceptance' } }),
  switcher('checked_by_default', { returnValue: 'true',  label: 'Checked by default', condition: { field_type: 'acceptance' } }),
  number('rows', { label: 'Rows', default: 4, condition: { field_type: 'textarea' } }),
  number('field_min', { label: 'Min', condition: { field_type: ['number', 'range', 'date'] } }),
  number('field_max', { label: 'Max', condition: { field_type: ['number', 'range', 'rating', 'date'] } }),
  number('field_step', { label: 'Step', condition: { field_type: ['number', 'range'] } }),
  code('field_html', { label: 'HTML', language: 'html', condition: { field_type: 'html' } }),
  select('width', { label: 'Column width', options: WIDTH_OPTIONS, default: '100', responsive: true, condition: { 'field_type!': ['hidden', 'step', 'honeypot'] } }),
  text('previous_button', { label: 'Previous button', condition: { field_type: 'step' } }),
  text('next_button', { label: 'Next button', condition: { field_type: 'step' } }),
  text('field_value', { label: 'Default value', dynamic: ['text'], condition: { 'field_type!': ['html', 'step', 'honeypot', 'acceptance'] } }),
  text('custom_id', { label: 'ID', description: 'Unique, letters, numbers and underscores only. Used in emails as [field id="…"].' }),
  text('autocomplete', { label: 'Autocomplete', placeholder: 'name, email, tel…', condition: noOptions }),
  text('bw_pattern', { label: 'Validation pattern', placeholder: '[0-9]{11}', description: 'Regular expression the value must match.', condition: noOptions }),
  text('bw_error', { label: 'Custom error message', condition: { 'field_type!': ['html', 'step', 'honeypot'] } }),
  json('bw_logic', { label: 'Conditional logic', description: 'Show or hide this field based on earlier answers.' }),
  text('css_classes', { label: 'CSS classes' }),
]

export const DEFAULT_FIELDS = [
  { _id: 'name', custom_id: 'name', field_type: 'text', field_label: 'Name', placeholder: 'Your name', width: '50', autocomplete: 'name' },
  { _id: 'email', custom_id: 'email', field_type: 'email', field_label: 'Email', placeholder: 'you@example.com', required: 'true', width: '50' },
  { _id: 'message', custom_id: 'message', field_type: 'textarea', field_label: 'Message', placeholder: 'How can we help?', required: 'true', width: '100' },
  { _id: 'hp', custom_id: 'hp', field_type: 'honeypot', field_label: '' },
]

export const formSections = [
  section('section_form_fields', 'Form fields', [
    text('form_name', { label: 'Form name', default: 'New form' }),
    repeater('form_fields', fieldControls, { label: 'Fields', titleField: 'field_label', default: DEFAULT_FIELDS }),
    select('input_size', { label: 'Input size', options: opts({ xs: 'Extra small', sm: 'Small', md: 'Medium', lg: 'Large', xl: 'Extra large' }), default: 'sm' }),
    switcher('show_labels', { returnValue: 'true',  label: 'Show labels', default: 'true' }),
    switcher('mark_required', { returnValue: 'true',  label: 'Mark required fields', default: 'true', condition: { show_labels: 'true' } }),
  ]),
  section('section_buttons', 'Buttons', [
    heading('heading_steps_buttons', 'Step buttons'),
    text('step_next_label', { label: 'Next', default: 'Next' }),
    text('step_previous_label', { label: 'Previous', default: 'Previous' }),
    heading('heading_submit_button', 'Submit button'),
    text('button_text', { label: 'Submit', default: 'Send' }),
    select('button_size', { label: 'Size', options: opts({ xs: 'Extra small', sm: 'Small', md: 'Medium', lg: 'Large', xl: 'Extra large' }), default: 'sm' }),
    select('button_width', { label: 'Column width', options: WIDTH_OPTIONS, default: '100', responsive: true }),
    choose('button_align', {
      label: 'Alignment',
      responsive: true,
      options: opts({ start: 'Start', center: 'Center', end: 'End', stretch: 'Justified' }),
      default: 'stretch',
      selectorsDictionary: {
        start: '--bw-btn-justify:flex-start;--bw-btn-w:auto',
        center: '--bw-btn-justify:center;--bw-btn-w:auto',
        end: '--bw-btn-justify:flex-end;--bw-btn-w:auto',
        stretch: '--bw-btn-justify:stretch;--bw-btn-w:100%',
      },
      selectors: { [W]: '{{VALUE}};' },
    }),
    text('button_css_id', { label: 'Button ID' }),
  ]),
  section('section_steps_settings', 'Steps', [
    select('step_type', {
      label: 'Step indicator',
      options: opts({ none: 'None', text: 'Labels', number: 'Numbers', number_text: 'Numbers and labels', progress_bar: 'Progress bar' }),
      default: 'number_text',
    }),
  ]),
  section('section_integration', 'Actions after submit', [
    select('submit_actions', {
      label: 'Actions',
      multiple: true,
      options: opts({ save: 'Save entry', notifications: 'Email notifications', email: 'Email (simple)', email2: 'Auto-reply (simple)', redirect: 'Redirect', webhook: 'Webhook', collection: 'Create document' }),
      default: ['save', 'notifications'],
    }),
  ]),
  section(
    'section_notifications',
    'Email notifications',
    [
      repeater(
        'bw_notifications',
        [
          text('name', { label: 'Name', default: 'Admin notification', description: 'Only shown here, to tell notifications apart.' }),
          switcher('enabled', { label: 'Active', default: 'yes' }),
          text('to', { label: 'Send to', shortcodes: true, placeholder: 'owner@example.com, sales@example.com', description: 'Separate addresses with commas. Leave empty for the site default. You can use [field id="email"].' }),
          text('cc', { label: 'Cc', shortcodes: true }),
          text('bcc', { label: 'Bcc', shortcodes: true }),
          text('subject', { label: 'Subject', default: 'New submission: {form_name}', shortcodes: true }),
          select('format', { label: 'Format', options: opts({ html: 'HTML', plain: 'Plain text' }), default: 'html' }),
          wysiwyg('message_html', { label: 'Message', default: DEFAULT_NOTIFICATION_HTML, shortcodes: true, condition: { 'format!': 'plain' } }),
          textarea('message_text', { label: 'Message', default: 'New submission from {form_name}:\n\n[all-fields]', shortcodes: true, rows: 8, condition: { format: 'plain' } }),
          switcher('wrap', { label: 'Use email layout', default: 'yes', description: 'Adds a header with your site name and a footer.', condition: { 'format!': 'plain' } }),
          heading('heading_sender', 'Sender'),
          text('from_email', { label: 'From email', placeholder: 'Site default' }),
          text('from_name', { label: 'From name', shortcodes: true, placeholder: 'Site name' }),
          text('reply_to', { label: 'Reply-to', shortcodes: true, placeholder: '[field id="email"]' }),
          heading('heading_routing', 'Conditions'),
          json('bw_route', { label: 'Send only when', description: 'Leave empty to always send.' }),
          heading('bw_email_preview', 'Preview'),
        ],
        {
          label: 'Notifications',
          titleField: 'name',
          addLabel: 'notification',
          default: [
            { _id: 'admin', name: 'Admin notification', enabled: 'yes', to: '', subject: 'New submission: {form_name}', format: 'html', message_html: DEFAULT_NOTIFICATION_HTML, wrap: 'yes', reply_to: '[field id="email"]' },
          ],
        },
      ),
    ],
    { condition: { submit_actions: 'notifications' } },
  ),
  section(
    'section_email',
    'Email (simple)',
    [
      text('email_to', { shortcodes: true, label: 'To', placeholder: 'admin@example.com', description: 'Separate emails with commas. Leave empty to use the site default.' }),
      text('email_subject', { shortcodes: true, label: 'Subject', default: 'New message from "{form_name}"' }),
      textarea('email_content', { shortcodes: true, label: 'Message', default: '[all-fields]', description: 'Use [all-fields] or [field id="email"] to insert answers.' }),
      text('email_from', { label: 'From email' }),
      text('email_from_name', { shortcodes: true, label: 'From name' }),
      text('email_reply_to', { shortcodes: true, label: 'Reply-to', default: '[field id="email"]' }),
      text('email_to_cc', { shortcodes: true, label: 'Cc' }),
      text('email_to_bcc', { shortcodes: true, label: 'Bcc' }),
    ],
    { condition: { submit_actions: 'email' } },
  ),
  section(
    'section_email_2',
    'Auto-reply (simple)',
    [
      text('email_to_2', { shortcodes: true, label: 'To', default: '[field id="email"]' }),
      text('email_subject_2', { shortcodes: true, label: 'Subject', default: 'We received your message' }),
      textarea('email_content_2', { shortcodes: true, label: 'Message', default: 'Thanks for reaching out. We will get back to you soon.\n\n[all-fields]' }),
      text('email_from_2', { label: 'From email' }),
      text('email_from_name_2', { label: 'From name' }),
      text('email_reply_to_2', { label: 'Reply-to' }),
    ],
    { condition: { submit_actions: 'email2' } },
  ),
  section('section_redirect', 'Redirect', [url('redirect_to', { shortcodes: true, label: 'Redirect to', dynamic: ['url'], description: 'Answers can be added with [field id="…"].' })], {
    condition: { submit_actions: 'redirect' },
  }),
  section(
    'section_webhook',
    'Webhook',
    [
      text('webhooks', { label: 'Webhook URL', placeholder: 'https://hooks.example.com/…' }),
      switcher('webhooks_advanced_data', { returnValue: 'true',  label: 'Send full data', description: 'Includes form details and submission metadata.' }),
    ],
    { condition: { submit_actions: 'webhook' } },
  ),
  section(
    'section_collection',
    'Create document',
    [
      text('bw_collection', { label: 'Collection', placeholder: 'leads', description: 'Collection slug. It must be allowed in the plugin settings.' }),
      repeater('bw_collection_mapping', [text('field', { label: 'Form field ID' }), text('target', { label: 'Document field' })], { label: 'Field mapping', titleField: 'target' }),
    ],
    { condition: { submit_actions: 'collection' } },
  ),
  section('section_form_options', 'Additional options', [
    text('form_id', { label: 'Form ID', description: 'Anchor id for the form, e.g. contact.' }),
    templatePicker('bw_pdf_template', { label: 'PDF template', templateType: 'pdf', description: 'Used when you print or save an entry as PDF. Leave empty for the newest PDF template.' }),
    switcher('custom_messages', { returnValue: 'true',  label: 'Custom messages' }),
    text('success_message', { label: 'Success', default: 'Thanks! Your message has been sent.', condition: { custom_messages: 'true' } }),
    text('error_message', { label: 'Error', default: 'Your submission could not be sent. Please check the highlighted fields.', condition: { custom_messages: 'true' } }),
    text('server_message', { label: 'Server error', default: 'Something went wrong on our side. Please try again in a moment.', condition: { custom_messages: 'true' } }),
    text('invalid_message', { label: 'Invalid value', default: 'Please enter a valid value.', condition: { custom_messages: 'true' } }),
    text('required_field_message', { label: 'Required field', default: 'This field is required.', condition: { custom_messages: 'true' } }),
  ]),

  /* ------------------------------ Style ------------------------------ */
  section(
    'section_form_style',
    'Form',
    [
      slider('column_gap', { label: 'Columns gap', responsive: true, units: ['px', 'em', 'rem', 'custom'], selectors: { [W]: '--bw-col-gap: {{SIZE}}{{UNIT}};' } }),
      slider('row_gap', { label: 'Rows gap', responsive: true, units: ['px', 'em', 'rem', 'custom'], selectors: { [W]: '--bw-row-gap: {{SIZE}}{{UNIT}};' } }),
      heading('heading_label', 'Label'),
      slider('label_spacing', { label: 'Spacing', responsive: true, units: ['px', 'em', 'rem', 'custom'], selectors: { [W]: '--bw-label-gap: {{SIZE}}{{UNIT}};' } }),
      color('label_color', { label: 'Text color', global: 'colors', selectors: { [L]: 'color: {{VALUE}};', [`${W} .bw-option label`]: 'color: {{VALUE}};' } }),
      color('mark_required_color', { label: 'Required mark color', selectors: { [`${W} .bw-mark-required .bw-field-label::after`]: 'color: {{VALUE}};' } }),
      ...typography('label_typography', { selector: `${L}, ${W} .bw-option label` }),
      heading('heading_html', 'HTML field'),
      slider('html_spacing', { label: 'Spacing', responsive: true, selectors: { [`${W} .bw-field-html`]: 'padding-block-end: {{SIZE}}{{UNIT}};' } }),
      color('html_color', { label: 'Text color', global: 'colors', selectors: { [`${W} .bw-field-html`]: 'color: {{VALUE}};' } }),
      ...typography('html_typography', { selector: `${W} .bw-field-html` }),
    ],
    { tab: 'style' },
  ),
  section(
    'section_field_style',
    'Fields',
    [
      color('field_text_color', { label: 'Text color', global: 'colors', selectors: { [F]: 'color: {{VALUE}};' } }),
      color('bw_placeholder_color', { label: 'Placeholder color', selectors: { [`${F}::placeholder`]: 'color: {{VALUE}}; opacity: 1;' } }),
      ...typography('field_typography', { selector: F }),
      color('field_background_color', { label: 'Background color', default: '#ffffff', global: 'colors', selectors: { [F]: 'background-color: {{VALUE}};' } }),
      color('field_border_color', { label: 'Border color', global: 'colors', selectors: { [F]: 'border-color: {{VALUE}};' } }),
      dimensions('field_border_width', {
        label: 'Border width',
        units: ['px', 'em', 'rem', 'custom'],
        selectors: { [F]: 'border-width: {{TOP}}{{UNIT}} {{RIGHT}}{{UNIT}} {{BOTTOM}}{{UNIT}} {{LEFT}}{{UNIT}};' },
      }),
      borderRadius('field_border_radius', { selector: F }),
      padding('bw_field_padding', F),
      slider('bw_field_height', { label: 'Min height', responsive: true, units: ['px', 'em', 'rem', 'custom'], selectors: { [`${W} input.bw-field, ${W} select.bw-field`]: 'min-height: {{SIZE}}{{UNIT}};' } }),
      ...boxShadow('bw_field_shadow', { selector: F }),
      heading('heading_field_focus', 'Focus'),
      color('bw_field_focus_border_color', { label: 'Border color', global: 'colors', selectors: { [`${F}:focus`]: 'border-color: {{VALUE}};' } }),
      color('bw_field_focus_ring_color', { label: 'Focus ring color', global: 'colors', selectors: { [W]: '--bw-ring: {{VALUE}};' } }),
      color('bw_field_focus_background', { label: 'Background color', selectors: { [`${F}:focus`]: 'background-color: {{VALUE}};' } }),
      heading('heading_choices', 'Checkboxes and radios'),
      color('bw_choice_accent', { label: 'Accent color', global: 'colors', selectors: { [W]: 'accent-color: {{VALUE}};' } }),
      slider('bw_choice_size', { label: 'Size', units: ['px', 'em', 'custom'], selectors: { [`${W} .bw-option input`]: 'width: {{SIZE}}{{UNIT}}; height: {{SIZE}}{{UNIT}};' } }),
      slider('bw_choice_gap', { label: 'Gap between options', units: ['px', 'em', 'custom'], selectors: { [`${W} .bw-options`]: 'gap: {{SIZE}}{{UNIT}};' } }),
      color('bw_rating_color', { label: 'Rating color', global: 'colors', selectors: { [W]: '--bw-rating: {{VALUE}};' } }),
    ],
    { tab: 'style' },
  ),
  section(
    'section_button_style',
    'Buttons',
    [
      ...typography('button_typography', { selector: `${BTN}, ${PREV}` }),
      ...border('button_border', { selector: `${BTN}, ${PREV}` }),
      borderRadius('button_border_radius', { selector: `${BTN}, ${PREV}` }),
      padding('button_text_padding', `${BTN}, ${PREV}`),
      ...boxShadow('bw_button_shadow', { selector: BTN }),
      heading('heading_next_submit_button', 'Submit and next'),
      color('button_background_color', { label: 'Background color', global: 'colors', selectors: { [BTN]: 'background-color: {{VALUE}};' } }),
      color('button_text_color', { label: 'Text color', global: 'colors', selectors: { [BTN]: 'color: {{VALUE}};' } }),
      color('button_border_color', { label: 'Border color', global: 'colors', condition: { 'button_border_border!': '' }, selectors: { [BTN]: 'border-color: {{VALUE}};' } }),
      heading('heading_next_submit_button_hover', 'Submit and next: hover'),
      color('button_background_hover_color', { label: 'Background color', global: 'colors', selectors: { [BTN_H]: 'background-color: {{VALUE}};' } }),
      color('button_hover_color', { label: 'Text color', global: 'colors', selectors: { [BTN_H]: 'color: {{VALUE}};' } }),
      color('button_hover_border_color', { label: 'Border color', global: 'colors', selectors: { [BTN_H]: 'border-color: {{VALUE}};' } }),
      heading('heading_previous_button', 'Previous'),
      color('previous_button_background_color', { label: 'Background color', global: 'colors', selectors: { [PREV]: 'background-color: {{VALUE}};' } }),
      color('previous_button_text_color', { label: 'Text color', global: 'colors', selectors: { [PREV]: 'color: {{VALUE}};' } }),
      color('previous_button_background_color_hover', { label: 'Hover background', global: 'colors', selectors: { [`${PREV}:hover`]: 'background-color: {{VALUE}};' } }),
      slider('hover_transition_duration', { label: 'Transition duration', units: ['ms'], selectors: { [`${BTN}, ${PREV}`]: 'transition-duration: {{SIZE}}ms;' } }),
    ],
    { tab: 'style' },
  ),
  section(
    'section_messages_style',
    'Messages',
    [
      ...typography('message_typography', { selector: `${W} .bw-form-message, ${W} .bw-field-error` }),
      color('success_message_color', { label: 'Success color', global: 'colors', selectors: { [`${W} .bw-form-message[data-state="success"]`]: 'color: {{VALUE}}; border-color: {{VALUE}};' } }),
      color('error_message_color', { label: 'Error color', global: 'colors', selectors: { [`${W} .bw-form-message[data-state="error"]`]: 'color: {{VALUE}}; border-color: {{VALUE}};' } }),
      color('inline_message_color', { label: 'Field error color', global: 'colors', selectors: { [W]: '--bw-danger: {{VALUE}};' } }),
    ],
    { tab: 'style' },
  ),
  section(
    'section_steps_style',
    'Steps',
    [
      ...typography('steps_typography', { selector: `${W} .bw-step-indicator` }),
      slider('steps_gap', { label: 'Gap', units: ['px', 'em', 'custom'], selectors: { [`${W} .bw-steps`]: 'gap: {{SIZE}}{{UNIT}};' } }),
      slider('steps_icon_size', { label: 'Number size', units: ['px', 'em', 'custom'], selectors: { [W]: '--bw-step-size: {{SIZE}}{{UNIT}};' } }),
      color('step_inactive_primary_color', { label: 'Inactive color', global: 'colors', selectors: { [W]: '--bw-step-inactive: {{VALUE}};' } }),
      color('step_active_primary_color', { label: 'Active color', global: 'colors', selectors: { [W]: '--bw-step-active: {{VALUE}};' } }),
      color('step_completed_primary_color', { label: 'Completed color', global: 'colors', selectors: { [W]: '--bw-step-done: {{VALUE}};' } }),
      color('step_progress_bar_color', { label: 'Progress color', global: 'colors', selectors: { [`${W} .bw-progress-bar`]: 'background-color: {{VALUE}};' } }),
      color('step_progress_bar_background_color', { label: 'Progress track color', global: 'colors', selectors: { [`${W} .bw-progress`]: 'background-color: {{VALUE}};' } }),
      slider('step_progress_bar_height', { label: 'Progress height', units: ['px'], selectors: { [`${W} .bw-progress`]: 'height: {{SIZE}}{{UNIT}};' } }),
      borderRadius('step_progress_bar_border_radius', { selector: `${W} .bw-progress, ${W} .bw-progress-bar` }),
    ],
    { tab: 'style', condition: { 'step_type!': 'none' } },
  ),
]
