/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrderStatus".
 */
export type OrderStatus = ('processing' | 'completed' | 'cancelled' | 'refunded') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    media: Media;
    users: User;
    'bw-templates': BwTemplate;
    'bw-form-entries': BwFormEntry;
    'bw-menus': BwMenu;
    'bw-widgets': BwWidget;
    addresses: Address;
    variants: Variant;
    variantTypes: VariantType;
    variantOptions: VariantOption;
    products: Product;
    carts: Cart;
    orders: Order;
    transactions: Transaction;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    variantTypes: {
      options: 'variantOptions';
    };
    products: {
      variants: 'variants';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'bw-templates': BwTemplatesSelect<false> | BwTemplatesSelect<true>;
    'bw-form-entries': BwFormEntriesSelect<false> | BwFormEntriesSelect<true>;
    'bw-menus': BwMenusSelect<false> | BwMenusSelect<true>;
    'bw-widgets': BwWidgetsSelect<false> | BwWidgetsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    variantTypes: VariantTypesSelect<false> | VariantTypesSelect<true>;
    variantOptions: VariantOptionsSelect<false> | VariantOptionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'bw-site-style': BwSiteStyle;
  };
  globalsSelect: {
    'bw-site-style': BwSiteStyleSelect<false> | BwSiteStyleSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
  /**
   * Generated by the Payload Ecommerce plugin
   */
  ecommerce: {
    collections: {
      addresses: Address;
      carts: Cart;
      customers?: User;
      orders: Order;
      products: Product;
      transactions: Transaction;
      variantOptions: VariantOption;
      variants: Variant;
      variantTypes: VariantType;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path. Use "home" for the front page.
   */
  slug: string;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  /**
   * Created by the visual editor. Use "Edit with Blockwright" instead of changing this by hand.
   */
  layout?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles?: ('admin' | 'customer')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Headers, footers and other site parts, shown wherever their display conditions match.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bw-templates".
 */
export interface BwTemplate {
  id: number;
  title: string;
  type:
    | 'header'
    | 'footer'
    | 'single-page'
    | 'single-post'
    | 'product'
    | 'single'
    | 'archive'
    | 'search-results'
    | 'error-404'
    | 'section'
    | 'page'
    | 'popup'
    | 'pdf';
  /**
   * Where to show it. Examples: include/general (entire site), include/front_page, include/singular/pages/12, exclude/singular/pages/12, include/not_found404.
   */
  conditions?: string[] | null;
  /**
   * Created by the visual editor. Use "Edit with Blockwright" instead of changing this by hand.
   */
  layout?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  pageSettings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Everything visitors sent through Blockwright forms.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bw-form-entries".
 */
export interface BwFormEntry {
  id: number;
  summary?: string | null;
  status?: ('new' | 'read' | 'archived') | null;
  formName?: string | null;
  elementId?: string | null;
  answers?:
    | {
        fieldId?: string | null;
        label?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Raw values keyed by field ID.
   */
  values?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  source?: {
    collection?: string | null;
    docId?: string | null;
    pageUrl?: string | null;
    referer?: string | null;
    userAgent?: string | null;
    ip?: string | null;
  };
  actionLog?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Navigation menus for the Nav menu widget. Links to pages follow slug changes automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bw-menus".
 */
export interface BwMenu {
  id: number;
  /**
   * For example "Main menu" or "Footer links".
   */
  title: string;
  items?:
    | {
        label: string;
        type?: ('page' | 'custom') | null;
        doc?: (number | null) | Page;
        /**
         * https://…, /path, #section, mailto: or tel:
         */
        url?: string | null;
        newTab?: boolean | null;
        nofollow?: boolean | null;
        submenu?:
          | {
              label: string;
              type?: ('page' | 'custom') | null;
              doc?: (number | null) | Page;
              /**
               * https://…, /path, #section, mailto: or tel:
               */
              url?: string | null;
              newTab?: boolean | null;
              nofollow?: boolean | null;
              subitems?:
                | {
                    label: string;
                    type?: ('page' | 'custom') | null;
                    doc?: (number | null) | Page;
                    /**
                     * https://…, /path, #section, mailto: or tel:
                     */
                    url?: string | null;
                    newTab?: boolean | null;
                    nofollow?: boolean | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Build your own widgets from fields and an HTML template. They appear in the editor under their category. Because they can contain raw HTML, only users allowed to post unfiltered HTML (the admin role by default) can create or edit them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bw-widgets".
 */
export interface BwWidget {
  id: number;
  title: string;
  /**
   * Unique ID, e.g. pricing-card. Changing it disconnects existing uses.
   */
  type: string;
  category?:
    | (
        | 'layout'
        | 'essentials'
        | 'media'
        | 'forms'
        | 'interactive'
        | 'marketing'
        | 'site'
        | 'commerce'
        | 'advanced'
        | 'custom'
      )
    | null;
  icon?:
    | (
        | 'arrow-right'
        | 'arrow-left'
        | 'arrow-up'
        | 'arrow-down'
        | 'chevron-right'
        | 'chevron-down'
        | 'check'
        | 'check-circle'
        | 'close'
        | 'plus'
        | 'minus'
        | 'star'
        | 'star-outline'
        | 'heart'
        | 'phone'
        | 'mail'
        | 'map-pin'
        | 'clock'
        | 'calendar'
        | 'user'
        | 'users'
        | 'home'
        | 'search'
        | 'cart'
        | 'bag'
        | 'truck'
        | 'credit-card'
        | 'wallet'
        | 'shield'
        | 'lock'
        | 'gift'
        | 'tag'
        | 'globe'
        | 'link'
        | 'download'
        | 'play'
        | 'play-circle'
        | 'camera'
        | 'image'
        | 'message'
        | 'bell'
        | 'settings'
        | 'info'
        | 'alert'
        | 'help'
        | 'quote'
        | 'bolt'
        | 'leaf'
        | 'sun'
        | 'award'
        | 'thumbs-up'
        | 'chart'
        | 'rocket'
        | 'facebook'
        | 'instagram'
        | 'x'
        | 'linkedin'
        | 'youtube'
        | 'whatsapp'
        | 'tiktok'
        | 'github'
        | 'pinterest'
      )
    | null;
  enabled?: boolean | null;
  description?: string | null;
  fields?:
    | {
        /**
         * lowercase_with_underscores
         */
        name: string;
        label?: string | null;
        type?:
          | (
              | 'text'
              | 'textarea'
              | 'wysiwyg'
              | 'number'
              | 'switcher'
              | 'select'
              | 'choose'
              | 'color'
              | 'media'
              | 'gallery'
              | 'url'
              | 'icon'
              | 'slider'
              | 'font'
              | 'typography'
              | 'background'
              | 'border'
              | 'border-radius'
              | 'box-shadow'
              | 'padding'
              | 'margin'
            )
          | null;
        /**
         * Default value (slider: 24px, icon: star)
         */
        default?: string | null;
        tab?: ('content' | 'style') | null;
        /**
         * Panel section name
         */
        section?: string | null;
        /**
         * For Select and Button group: one option per line, "Label|value".
         */
        options?: string | null;
        /**
         * CSS selector, e.g. {{WRAPPER}} h3
         */
        selector?: string | null;
        /**
         * Declaration, e.g. color: {{VALUE}}; or font-size: {{SIZE}}{{UNIT}};
         */
        css?: string | null;
        /**
         * Different values per device
         */
        responsive?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * HTML with placeholders: {{ field }} (escaped), {{{ field }}} (HTML), {{#if field}}…{{else}}…{{/if}}, {{#each items}}{{ this.text }}{{/each}}, {{icon field}}, {{link field}}, {{ image.url }}.
   */
  template: string;
  /**
   * Loaded once per page when the widget is used. "selector" targets this widget.
   */
  css?: string | null;
  /**
   * Optional. A full definition replaces the Fields tab: { "sections": [{ "id": "content", "label": "Content", "tab": "content", "controls": [{ "name": "title", "type": "text", "label": "Title" }, { "name": "title_typography", "type": "typography", "selector": "{{WRAPPER}} h3" }] }] }
   */
  definition?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: number;
  customer?: (number | null) | User;
  title?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  company?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  state?: string | null;
  postalCode?: string | null;
  country:
    | 'US'
    | 'GB'
    | 'CA'
    | 'AU'
    | 'AT'
    | 'BE'
    | 'BR'
    | 'BG'
    | 'CY'
    | 'CZ'
    | 'DK'
    | 'EE'
    | 'FI'
    | 'FR'
    | 'DE'
    | 'GR'
    | 'HK'
    | 'HU'
    | 'IN'
    | 'IE'
    | 'IT'
    | 'JP'
    | 'LV'
    | 'LT'
    | 'LU'
    | 'MY'
    | 'MT'
    | 'MX'
    | 'NL'
    | 'NZ'
    | 'NO'
    | 'PL'
    | 'PT'
    | 'RO'
    | 'SG'
    | 'SK'
    | 'SI'
    | 'ES'
    | 'SE'
    | 'CH';
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: number;
  /**
   * Used for administrative purposes, not shown to customers. This is populated by default.
   */
  title?: string | null;
  product: number | Product;
  options: (number | VariantOption)[];
  inventory?: number | null;
  priceInUSDEnabled?: boolean | null;
  priceInUSD?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  inventory?: number | null;
  enableVariants?: boolean | null;
  variantTypes?: (number | VariantType)[] | null;
  variants?: {
    docs?: (number | Variant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  priceInUSDEnabled?: boolean | null;
  priceInUSD?: number | null;
  title: string;
  slug: string;
  gallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes".
 */
export interface VariantType {
  id: number;
  label: string;
  name: string;
  options?: {
    docs?: (number | VariantOption)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions".
 */
export interface VariantOption {
  id: number;
  _variantOptions_options_order?: string | null;
  variantType: number | VariantType;
  label: string;
  /**
   * should be defaulted or dynamic based on label
   */
  value: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  secret?: string | null;
  customer?: (number | null) | User;
  purchasedAt?: string | null;
  status?: ('active' | 'purchased' | 'abandoned') | null;
  subtotal?: number | null;
  currency?: 'USD' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  shippingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  customer?: (number | null) | User;
  customerEmail?: string | null;
  transactions?: (number | Transaction)[] | null;
  status?: OrderStatus;
  amount?: number | null;
  currency?: 'USD' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  billingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  status: 'pending' | 'processing' | 'succeeded' | 'failed' | 'cancelled' | 'expired' | 'refunded';
  customer?: (number | null) | User;
  customerEmail?: string | null;
  order?: (number | null) | Order;
  cart?: (number | null) | Cart;
  amount?: number | null;
  currency?: 'USD' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'bw-templates';
        value: number | BwTemplate;
      } | null)
    | ({
        relationTo: 'bw-form-entries';
        value: number | BwFormEntry;
      } | null)
    | ({
        relationTo: 'bw-menus';
        value: number | BwMenu;
      } | null)
    | ({
        relationTo: 'bw-widgets';
        value: number | BwWidget;
      } | null)
    | ({
        relationTo: 'addresses';
        value: number | Address;
      } | null)
    | ({
        relationTo: 'variants';
        value: number | Variant;
      } | null)
    | ({
        relationTo: 'variantTypes';
        value: number | VariantType;
      } | null)
    | ({
        relationTo: 'variantOptions';
        value: number | VariantOption;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  layout?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bw-templates_select".
 */
export interface BwTemplatesSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  conditions?: T;
  layout?: T;
  pageSettings?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bw-form-entries_select".
 */
export interface BwFormEntriesSelect<T extends boolean = true> {
  summary?: T;
  status?: T;
  formName?: T;
  elementId?: T;
  answers?:
    | T
    | {
        fieldId?: T;
        label?: T;
        value?: T;
        id?: T;
      };
  values?: T;
  source?:
    | T
    | {
        collection?: T;
        docId?: T;
        pageUrl?: T;
        referer?: T;
        userAgent?: T;
        ip?: T;
      };
  actionLog?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bw-menus_select".
 */
export interface BwMenusSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        label?: T;
        type?: T;
        doc?: T;
        url?: T;
        newTab?: T;
        nofollow?: T;
        submenu?:
          | T
          | {
              label?: T;
              type?: T;
              doc?: T;
              url?: T;
              newTab?: T;
              nofollow?: T;
              subitems?:
                | T
                | {
                    label?: T;
                    type?: T;
                    doc?: T;
                    url?: T;
                    newTab?: T;
                    nofollow?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bw-widgets_select".
 */
export interface BwWidgetsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  category?: T;
  icon?: T;
  enabled?: T;
  description?: T;
  fields?:
    | T
    | {
        name?: T;
        label?: T;
        type?: T;
        default?: T;
        tab?: T;
        section?: T;
        options?: T;
        selector?: T;
        css?: T;
        responsive?: T;
        id?: T;
      };
  template?: T;
  css?: T;
  definition?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  customer?: T;
  title?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  postalCode?: T;
  country?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  title?: T;
  product?: T;
  options?: T;
  inventory?: T;
  priceInUSDEnabled?: T;
  priceInUSD?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes_select".
 */
export interface VariantTypesSelect<T extends boolean = true> {
  label?: T;
  name?: T;
  options?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions_select".
 */
export interface VariantOptionsSelect<T extends boolean = true> {
  _variantOptions_options_order?: T;
  variantType?: T;
  label?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  inventory?: T;
  enableVariants?: T;
  variantTypes?: T;
  variants?: T;
  priceInUSDEnabled?: T;
  priceInUSD?: T;
  title?: T;
  slug?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  secret?: T;
  customer?: T;
  purchasedAt?: T;
  status?: T;
  subtotal?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  customer?: T;
  customerEmail?: T;
  transactions?: T;
  status?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  billingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  status?: T;
  customer?: T;
  customerEmail?: T;
  order?: T;
  cart?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global colors, fonts and layout used by every Blockwright page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bw-site-style".
 */
export interface BwSiteStyle {
  id: number;
  siteName?: string | null;
  siteDescription?: string | null;
  /**
   * Public URL, e.g. https://example.com
   */
  siteUrl?: string | null;
  logo?: (number | null) | Media;
  /**
   * Referenced by widgets as global colors. Changing a color updates it everywhere.
   */
  colors?:
    | {
        title: string;
        /**
         * Lowercase id, e.g. primary
         */
        colorId: string;
        /**
         * Hex, rgb() or hsl()
         */
        color: string;
        id?: string | null;
      }[]
    | null;
  typography?:
    | {
        title: string;
        typoId: string;
        /**
         * Google Fonts family, e.g. Inter
         */
        fontFamily?: string | null;
        /**
         * px
         */
        fontSize?: number | null;
        fontWeight?: ('default' | '300' | '400' | '500' | '600' | '700' | '800') | null;
        /**
         * e.g. 1.5
         */
        lineHeight?: number | null;
        /**
         * px
         */
        letterSpacing?: number | null;
        id?: string | null;
      }[]
    | null;
  fontProvider?: ('google' | 'none') | null;
  /**
   * Content width of boxed frames, in px.
   */
  containerWidth?: number | null;
  /**
   * Default gap between elements, in px.
   */
  elementGap?: number | null;
  /**
   * Leave optional breakpoints empty to turn them off.
   */
  breakpoints?: {
    mobile?: number | null;
    mobileExtra?: number | null;
    tablet?: number | null;
    tabletExtra?: number | null;
    laptop?: number | null;
    widescreen?: number | null;
  };
  /**
   * Added to every Blockwright page.
   */
  customCss?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bw-site-style_select".
 */
export interface BwSiteStyleSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  siteUrl?: T;
  logo?: T;
  colors?:
    | T
    | {
        title?: T;
        colorId?: T;
        color?: T;
        id?: T;
      };
  typography?:
    | T
    | {
        title?: T;
        typoId?: T;
        fontFamily?: T;
        fontSize?: T;
        fontWeight?: T;
        lineHeight?: T;
        letterSpacing?: T;
        id?: T;
      };
  fontProvider?: T;
  containerWidth?: T;
  elementGap?: T;
  breakpoints?:
    | T
    | {
        mobile?: T;
        mobileExtra?: T;
        tablet?: T;
        tabletExtra?: T;
        laptop?: T;
        widescreen?: T;
      };
  customCss?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}